# Generated by Django 2.2 on 2020-12-06 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('picture', models.CharField(blank=True, max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_mentee', models.BooleanField(blank=True, default=False)),
                ('is_mentor', models.BooleanField(blank=True, default=False)),
                ('is_client', models.BooleanField(blank=True, default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('mobile_token', models.CharField(max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='companies_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=20)),
                ('coupon_code', models.CharField(max_length=30)),
                ('coupon_amount', models.PositiveIntegerField(null=True)),
                ('coupon_percentage', models.SmallIntegerField(null=True)),
                ('active_status', models.SmallIntegerField()),
                ('coupon_minimum_cart_price', models.PositiveIntegerField(null=True)),
                ('coupon_type', models.CharField(max_length=20)),
                ('new_user_coupon', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('College_Name', models.CharField(max_length=200)),
                ('Level_of_Course', models.CharField(max_length=200)),
                ('Degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='degree_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mentor_schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mentor_id', models.IntegerField()),
                ('Start_datetime', models.DateTimeField()),
                ('End_datetime', models.DateTimeField()),
                ('Status', models.IntegerField(default=1)),
                ('Is_scheduled', models.IntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Session_name', models.CharField(max_length=100)),
                ('charge', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mentor_topics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mentor_id', models.IntegerField()),
                ('Linked_url', models.URLField()),
                ('Skills', models.TextField()),
                ('Session_121', models.IntegerField(default=1)),
                ('Webinar', models.IntegerField(default=1)),
                ('Webinar_topics', models.CharField(max_length=1000)),
                ('Webinar_charge', models.CharField(max_length=1000)),
                ('Status', models.IntegerField(default=1)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('mentor_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(max_length=1000, upload_to='images_media/')),
            ],
        ),
        migrations.CreateModel(
            name='sales_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Schedule_id', models.IntegerField()),
                ('Mentor_id', models.IntegerField()),
                ('Mentee_id', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Payment_id', models.CharField(max_length=100)),
                ('Is_active', models.SmallIntegerField(default=1)),
                ('Session_name', models.CharField(max_length=30)),
                ('Status', models.SmallIntegerField(default=0)),
                ('Status_updated_at', models.DateTimeField(auto_now=True)),
                ('mentee_feedback_id', models.IntegerField(null=True)),
                ('Mentor_feedback_id', models.IntegerField(null=True)),
                ('Video_link', models.URLField(default='https://meet.google.com')),
                ('Parent_id', models.IntegerField(null=True)),
                ('User_order_id', models.CharField(max_length=30)),
                ('Mentee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mentee_phonenumber', models.CharField(max_length=15)),
                ('Mentee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session_charge', models.PositiveIntegerField(null=True)),
                ('coupon_amount', models.PositiveIntegerField(null=True)),
                ('coupon_id', models.CharField(max_length=30, null=True)),
                ('final_price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='skills_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='voice_call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('token_id', models.TextField()),
                ('channel_name', models.CharField(max_length=20)),
                ('expiration_time', models.IntegerField(null=True)),
                ('request_type', models.CharField(max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=100)),
                ('Sales_Order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentee.sales_order')),
            ],
        ),
        migrations.CreateModel(
            name='MentorFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linkedin_url', models.TextField(max_length=400, null=True)),
                ('skills', models.TextField(default='[]', null=True)),
                ('session_121', models.BooleanField(default=0, null=True)),
                ('webinar', models.BooleanField(default=0, null=True)),
                ('webinar_topics', models.TextField(default='[]', null=True)),
                ('webinar_min', models.SmallIntegerField(null=True)),
                ('webinar_max', models.SmallIntegerField(null=True)),
                ('details_filled', models.BooleanField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mentor_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.URLField(null=True)),
                ('languages', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.TextField(null=True)),
                ('professional_details', models.TextField(max_length=15, null=True)),
                ('educational_details', models.TextField(max_length=15, null=True)),
                ('industry_exp', models.FloatField(null=True)),
                ('skills', models.TextField(default='[]')),
                ('contact_no', models.BigIntegerField(null=True)),
                ('country_code', models.CharField(max_length=7, null=True)),
                ('rating', models.FloatField(null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenteeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.CharField(blank=True, max_length=15)),
                ('college', models.CharField(blank=True, max_length=300, null=True)),
                ('degree', models.CharField(blank=True, max_length=300, null=True)),
                ('course', models.CharField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('industry_exp', models.SmallIntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, default='[]')),
                ('goal_defined', models.BooleanField(blank=True, null=True)),
                ('same_profession', models.BooleanField(blank=True, null=True)),
                ('career1', models.CharField(blank=True, max_length=300, null=True)),
                ('career2', models.CharField(blank=True, max_length=300, null=True)),
                ('career_list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mentee_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.IntegerField()),
                ('star_rating', models.FloatField(null=True)),
                ('comments', models.TextField(null=True)),
                ('Sales_Order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentee.sales_order')),
            ],
        ),
    ]
