# Generated by Django 2.2 on 2021-01-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('image_link', models.URLField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('about_the_mentor', models.TextField(blank=True, null=True)),
                ('about_the_webinar', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('key_takeaways', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
