# Generated by Django 3.0.5 on 2020-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor_schedule',
            old_name='charge',
            new_name='mentor_charge',
        ),
        migrations.AddField(
            model_name='mentor_schedule',
            name='session_charge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor_schedule',
            name='Is_scheduled',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentor_schedule',
            name='Status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
