# Generated by Django 3.0.5 on 2020-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_auto_20201211_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentee_id', models.IntegerField()),
                ('Current_balance', models.FloatField()),
                ('Previous_balance', models.FloatField()),
                ('Amount_changed', models.FloatField()),
                ('Txn_order_id', models.CharField(max_length=100)),
                ('Status', models.SmallIntegerField()),
                ('Voice_id', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
