# Generated by Django 2.2 on 2021-01-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_webinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='about_the_webinar',
            new_name='about_the_event',
        ),
    ]
