# Generated by Django 3.0.5 on 2020-12-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Mentee_id',
            new_name='mentee_id',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Txn_order_id',
            new_name='txn_order_id',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Voice_id',
            new_name='voice_id',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='Sales_Order',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Amount_changed',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Current_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Previous_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='amount_changed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='previous_balance',
            field=models.FloatField(default=0),
        ),
    ]
