# Generated by Django 2.2 on 2021-01-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0004_auto_20210124_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='webinar',
            new_name='events',
        ),
    ]
