# Generated by Django 3.0.5 on 2020-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0004_auto_20201212_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='User_order_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
