# Generated by Django 2.2 on 2021-01-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0005_auto_20210124_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor_bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.IntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('account_number', models.CharField(max_length=50)),
            ],
        ),
    ]
