# Generated by Django 2.2 on 2020-12-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0005_auto_20201213_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order',
            name='wallet_id',
            field=models.IntegerField(null=True),
        ),
    ]
