# Generated by Django 2.2 on 2020-12-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0006_sales_order_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_order',
            name='wallet_id',
        ),
        migrations.AddField(
            model_name='sales_order',
            name='wallet_used',
            field=models.BooleanField(default=False),
        ),
    ]
