# Generated by Django 2.2 on 2021-01-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0007_auto_20210126_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_bank_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
