# Generated by Django 2.2 on 2020-12-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0007_auto_20201214_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order',
            name='wallet_amount',
            field=models.IntegerField(null=True),
        ),
    ]
