# Generated by Django 2.2 on 2021-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0008_mentor_bank_details_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteedetails',
            name='school_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
