# Generated by Django 2.2 on 2020-12-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0008_sales_order_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='remarks',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
