# Generated by Django 2.2 on 2020-12-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0009_wallet_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
