# Generated by Django 2.2 on 2020-12-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0010_auto_20201214_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='User_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
