# Generated by Django 3.0.5 on 2020-12-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0011_auto_20201214_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite_mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_id', models.IntegerField()),
                ('mentor_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='razorpay_signature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='Payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
