# Generated by Django 2.2 on 2021-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0011_auto_20210131_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('image', models.ImageField(max_length=200, upload_to='profile_picture/')),
                ('image_link', models.URLField(null=True)),
            ],
        ),
    ]
