# Generated by Django 2.2 on 2020-12-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0012_auto_20201217_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_id', models.IntegerField()),
                ('mentor_id', models.IntegerField()),
                ('session_name', models.CharField(max_length=50)),
                ('mentor_notify', models.BooleanField(default=True)),
                ('mentee_notify', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
