# Generated by Django 2.2 on 2020-12-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0013_request_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('channel_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('is_mentee', models.BooleanField()),
                ('sales_order_id', models.IntegerField(null=True)),
                ('reason', models.IntegerField()),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
