# Generated by Django 2.2 on 2021-02-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0013_event_sales_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('star_rating', models.SmallIntegerField(null=True)),
                ('comments', models.TextField(null=True)),
                ('event_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentee.event_sales_order')),
            ],
        ),
    ]
