# Generated by Django 2.2 on 2020-12-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0014_callhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callhistory',
            old_name='sales_order_id',
            new_name='schedule_id',
        ),
    ]
