# Generated by Django 2.2 on 2021-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0016_auto_20201223_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_schedule',
            name='mentee_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mentee_feedback',
            name='star_rating',
            field=models.SmallIntegerField(null=True),
        ),
    ]
