# Generated by Django 2.2 on 2021-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0017_auto_20210104_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor_profile_clicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_id', models.IntegerField()),
                ('mentor_id', models.IntegerField()),
                ('session_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
