# Generated by Django 2.2 on 2021-01-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0018_mentor_profile_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills_career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
