# Generated by Django 2.2 on 2021-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0019_skills_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteedetails',
            name='education_level',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
