# Generated by Django 2.2 on 2021-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0020_menteedetails_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorflow',
            name='invalid_url',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
