# Generated by Django 2.2 on 2021-01-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0021_mentorflow_invalid_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorflow',
            old_name='webinar_max',
            new_name='webinar_charge',
        ),
        migrations.RemoveField(
            model_name='mentorflow',
            name='webinar_min',
        ),
        migrations.AddField(
            model_name='mentorflow',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
